---
-   name: install dependentcs for spack
    ansible.builtin.dnf:
        name:
        -   "@Development tools"
        -   gcc-gfortran
        -   lsb_release
        -   python3
        -   unzip
        state: present

-   name: create folder for spack
    ansible.builtin.file:
        path: "{{ (sharedSoftwarePath, 'spack') | path_join }}"
        state: directory

-   name: Download spack in fixed version
    ansible.builtin.unarchive:
        src: "https://github.com/spack/spack/archive/refs/tags/v{{ spackVersion }}.tar.gz"
        dest: "{{ (sharedSoftwarePath, 'spack') | path_join }}"
        remote_src: yes

-   name: set spackVersionName (spack-<version>)
    ansible.builtin.set_fact:
        spackVersionName: "spack-{{ spackVersion }}"

-   name: remove windows and apple stuff
    ansible.builtin.file:
        state: absent
        path: "{{ (sharedSoftwarePath, 'spack', spackVersionName, item) | path_join }}"
    loop:
    -   "bin/spack.bat"
    -   "bin/spack.ps1"
    -   "bin/spack_cmd.bat"
    -   "bin/spack_pwsh.ps1"
    -   "bin/haspywin.py"
    -   "etc/spack/defaults/windows"
    -   "etc/spack/defaults/darwin"
    -   "share/spack/setup-env.bat"
    -   "share/spack/setup-env.ps1"
